# Generated by Django 2.2.5 on 2019-09-22 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190922_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='persons_assign_to_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
