# Generated by Django 2.2.5 on 2019-09-23 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190922_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='update',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='update',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='bookinstance',
            old_name='create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bookinstance',
            old_name='update',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='update',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='update',
            new_name='updated_on',
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_place',
            field=models.CharField(blank=True, default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance', to='app.Book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_book_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_assign_to_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
